### ISSUE TITLE
Suggest existing tags by typeahead search

### ISSUE THREAD

**Issue by andibraeu** [HackspaceJena/calcifer#12]

**Comment by enko** [comment]
This looks very good:

http://brianreavis.github.io/selectize.js/

**Comment by andibraeu** [comment]
implemented this for linksink: https://github.com/andibraeu/LinkSink/commit/98ced088bf29427b2602138216126318bb57267b

take a look at: http://linksink.ishalt.so/links/paderborn-knackt-die-300-aktiven-knoten/edit
