### ISSUE TITLE
Feature Request: Termin als Vorlage nutzen

### ISSUE THREAD

**Issue by someuser89** [HackspaceJena/calcifer#46]
Hallo,

eine Idee für ein Feature. Aus gehend von einem abberufenden Termin eine weitere Option bereitstellen, um das Eingabeformular aus Neuer Termin vor ausgefüllt zu erhalten, mit den Werten aus den geöffneten Termin.

Man sollte aber sicherstellen, das beim erstellen auch Werte wurde und nicht anschließend zwei identische Termine existieren.

**Comment by enko** [comment]
Es gibt doch schon die Funktion „Kopieren“, das ist doch schon die halbe Arbeit?

**Comment by someuser89** [comment]
Oh, Super! 8)
