### ISSUE TITLE
php composer update fails

### ISSUE THREAD

**Issue by andibraeu** [HackspaceJena/calcifer#47]
Problem:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package enko/relativedateparser could not be found in any version, there may be a typo in the package name

Cause: There's no version v0.5 on github for relativedateparser

**Comment by enko** [comment]
This is realy strange, because I already pushed a 0.5 somewhen in may and also deployed that at https://calcifer.datenknoten.me/.

Please check again.

**Comment by enko** [comment]
I ran into this today and I think I fixed it by pushing the missing changes to HackspaceJena/relativedateparser and taging a new release and changing to repository over there at [packagist](https://packagist.org/packages/enko/relativedateparser).
