### ISSUE TITLE
Feature Request: Participants

### ISSUE THREAD

**Issue by AiyionPrime** [HackspaceJena/calcifer#52]
Have you ever thought about a doodle like participant management?
So, that a visitor may mark his name as attendee for an upcoming event.
An optional small login/register script may give the user the opportunity to list all his upcoming Events.

Doodle is a great thing, but as it has neither an api, nor does it support repeating Events like calcifer does, it does not fit our needs anymore.
Nice project, by the way.

**Comment by enko** [comment]
Sounds like a good idea, maybe in a future version.

**Comment by AiyionPrime** [comment]
Sorry, we've moved away from using this.
Bye
