### ISSUE TITLE
defekter export als ical

### ISSUE THREAD

**Issue by StephanRichter** [HackspaceJena/calcifer#53]
Beim ical-Export gibt es offenbar Probleme mit Umlauten:

ich habe gerade https://calcifer.datenknoten.me/all.ics abgerufen, weil ich an einem ical-Parser für OpenCloudCal rumschraube. Und der meldet fehlerhaftes ical-Format.
Soweit ich das sehe, besteht folgendes Problem:

Zeilenumbrüche im Termin werden nicht, wie vom RFC ( https://tools.ietf.org/html/rfc5545#section-3.3.11 )  gefordert mit \n im ical encoded. 
Das führt dazu, dass Zeilenumbrüche im ical auftauchen, wo keine sein dürfen.

*snippet*
```
DESCRIPTION:Der Jahresbrunch  ist eine tolle Gelegenheit - bei leckere
 m Essen - gemeinsam auf das BDP-Jahr 2015 zurückzublicken.
Wir möch
 ten ausdrücklich alle einladen, die an Freizeiten, Veranstaltungen, P
 rojekten und Aktionen dabei waren
```
Hier stand im Originaltext ein newline hinter dem "zurückblicken", welches unescpaed in das ical übernommen wurde.

Richtig sollte es so aussehen:
```
DESCRIPTION:Der Jahresbrunch  ist eine tolle Gelegenheit - bei leckere
 m Essen - gemeinsam auf das BDP-Jahr 2015 zurückzublicken.\n Wir möch
 ten ausdrücklich alle einladen, die an Freizeiten, Veranstaltungen, P
 rojekten und Aktionen dabei waren
```

**Comment by StephanRichter** [comment]
ok, thats a bug in an imported lib. the patch for the lib is here: https://github.com/jasvrcek/ICS/compare/3d79628c60f625...keawe-software:2fb798fc90a

**Comment by enko** [comment]
Deployed the fix with 1b0ae14c70cc241f5647a91975879739a3211c7b.

Please close the issue if this fixes the issue for you.

**Comment by StephanRichter** [comment]
Seems to work now.
